### ISSUE TITLE
Error while training custom dataset

### ISSUE THREAD

**Issue by RVT123123** [EllenRushe/AudioAnomalyDetectionWaveNet#2] opened 2021-06-01 08:51 UTC
I have generated tfrecords with my own dataset and started training it. But got errors: 

ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    train(train_list, params, args.scene_name)
  File "/media_mayya/ravite/Wave_Net_Github_Repo/wav_latest/experiment/train.py", line 57, in train
    steps=int(np.ceil(num_train_examples/params.batch_size))*params.num_epochs
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1173, in _train_model_default
    saving_listeners)
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 583, in run
    run_metadata=run_metadata)
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1059, in run
    run_metadata=run_metadata)
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1150, in run
    raise six.reraise(*original_exc_info)
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1135, in run
    return self._sess.run(*args, **kwargs)
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1215, in run
    run_metadata=run_metadata))
  File "/home/anand/anaconda3/envs/aud_env/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 635, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

**Comment by EllenRushe** [comment] 2021-06-01 11:00
Hi there,

Nan values in the loss during training can be due to multiple issues. 

Especially since this is your own dataset, the first thing I would do is check for inf/-inf  values and non-numerical types that may have creeped into your training data which might be the culprit.  

If this is not the case, I think the problem is likely to be exploding gradients.  I would take a look at the many ways that exploding gradients can be mitigated (i.e. [normalising your custom dataset](https://en.wikipedia.org/wiki/Feature_scaling), increasing batch size,  lower learning rate etc. ). This is a common enough problem in neural network training that there have been[ lists of common causes](https://datascience.stackexchange.com/questions/68331/keras-sequential-model-returns-loss-nan) compiled that you might want to take a look at. 

Hope this helps!

**Comment by RVT123123** [comment] 2021-06-03 03:29
HI, There?

Thanks for your quick response and suggestion.
Unfortunately none of the solution works for me.
Is it the sample rate difference between my own data and yours data is making difference. my sample rate is 24500.

**Comment by EllenRushe** [comment] 2021-06-03 14:14
Thanks for the info. It's a little difficult to know what is causing the error without an understanding of how your pre-processing was done, but this setup was  for data quantised to 8-bit using mu-law companding (I'm not sure if you completed this pre-processing step) so this is perhaps where you're running into issues. 

What might help you is to take a look at utils/LoadData.py This runs through all the preprocessing that was done and you can adapt this to your setup (in particular take a look at lines 102 -120). It would also be helpful to check that the inputs are as expected before they enter the model. This will help you locate where the Nan values are occurring.

**Comment by EllenRushe** [comment] 2021-06-08 17:01
Hi,

Yes you are right about the dilation alternating from 1 to 2. This makes the receptive field smaller in order to prevent a large number of trailing zeros which would occur if the originally proposed number of dilations were used (I might remove the comment to avoid confusion). This is specific to this work and there is nothing stopping you from increasing the number of stacks if you want to, just increase num_stacks in HParams.yaml  to increase the number of dilations to your liking. Closing this now due to being a different topic that in the original issue.

**Closed by EllenRushe** 2021-06-08 17:01 UTC
